### ISSUE TITLE
[ubuntu2{2,4}.04-arm] docker commands unexpectedly slow to execute

### ISSUE THREAD

**Issue by sveitser** [actions/partner-runner-images#101]
**Type of issue**
- [ ] Error when running a workflow.
- [ ] Request for additional tools or software for an existing image.
- [ ] Request for a new image, Linux or Windows.
- [x] Other

**Describe the issue**
I noticed that on the public arm runners the `docker/setup-buildx-action@v3` takes 20s to 1 minute whereas on the public x86 runners it only takes 5-10 seconds.

The action calls some docker commands. Commands like `docker info` and `docker version` used by the action are unexpectedly slow **the first time they are executed**. If we call the docker commands manually before using the action the action runs faster but overall we're still left with much longer runtime than on x86.

The docker version on the arm runners is quite old compared to the `ubuntu-latest` runners, but I don't know if this has anything to do with this issue.

```
[command]/usr/bin/docker version				[command]/usr/bin/docker version
Client: Docker Engine - Community				Client: Docker Engine - Community
 Version:           28.0.4				      |	 Version:           26.1.3
 API version:       1.48				      |	 API version:       1.45
 Go version:        go1.23.7				      |	 Go version:        go1.21.10
 Git commit:        b8034c0				      |	 Git commit:        b72abbb
 Built:             Tue Mar 25 15:07:16 2025		      |	 Built:             Thu May 16 08:40:13 2024
 OS/Arch:           linux/amd64				      |	 OS/Arch:           linux/arm64
```

**To Reproduce**
```
name: docker

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  docker_build:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: docker version
        run: docker version
      - name: docker info
        run: docker info
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
```

**Expected behavior**
It should take roughly the same time to run these docker commands on the ARM runner compared to the x86 runners.

**Screenshots**
x86:
![Image](https://github.com/user-attachments/assets/303d1472-42c0-491f-bd4a-4324307ae967)

ARM:
![Image](https://github.com/user-attachments/assets/67c63266-92dd-4b99-ba70-5bfe08adfd92)

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04 or Ubuntu 24.04]

**Additional context**

[job-logs-docker-arm.txt](https://github.com/user-attachments/files/20587636/job-logs-docker-arm.txt)
