### ISSUE TITLE
Windows ARM64 image is missing Microsoft Visual C++

### ISSUE THREAD

**Issue by yorickdowne** [actions/partner-runner-images#19]
The Windows ARM64 runner image is missing Microsoft Visual Studio, or at least its C++ component.

As a result, `pip install wheel` fails after using the `setup-python` action. See https://github.com/actions/setup-python/issues/931

The error message encountered is: `distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/`

Looking at the Windows 2022 amd64 runner image, development tool dependencies appear to be part of the image itself. Hence this issue.

**Comment by jasonrandrews** [comment]
Hi @yorickdowne 

A new Windows image for ARM64 is being prepared, and it includes Visual Studio and other development tools. 

I don't have a date, but it's quite close to being available.

**Comment by dennisameling** [comment]
@jasonrandrews will Git for Windows also be included in the new image? I'm currently [getting this warning](https://github.com/dennisameling-org/git-for-windows-automation/actions/runs/10754569454/job/29825316692#step:2:34):

```
The repository will be downloaded using the GitHub REST API
To create a local Git repository instead, add Git 2.18 or higher to the PATH
```

Because Git isn't installed, some other commands in my pipeline are failing. I worked around it by just [installing it manually](https://github.com/dennisameling-org/git-for-windows-automation/blob/github-hosted-runners/azure-self-hosted-runners/post-deployment-script.ps1#L160) for now, but it still caused some issues later in the pipeline because it expects Git to be available on the PATH. Manually adding it to `GITHUB_PATH` doesn't seem to work for all scenarios, so it'd be great if your image will have it baked in.

Please note that Git for Windows ARM64 support [is being worked on](https://github.com/git-for-windows/git/issues/3107) (GitHub-hosted ARM64 runners for OSS would help a lot there), but the x64 version of GfW should be fine for now as Windows can emulate it.

Thanks!

**Comment by jasonrandrews** [comment]
Hi @dennisameling,

The emulated Git is in the image and works fine.

**Comment by yorickdowne** [comment]
Sounds like the new image is close!

Please also document it here when it gets released: https://github.com/actions/partner-runner-images?tab=readme-ov-file#available-images

**Comment by yorickdowne** [comment]
Do you have an update on this?

**Comment by jasonrandrews** [comment]
The Windows image build is complete and the GitHub Actions integration testing starts next week. Hopefully, not too much longer, sorry for the delay. We had a lot of issues beyond our control.

**Comment by lemonmojo** [comment]
@jasonrandrews What's the current status? We're eagerly awaiting a new Win on ARM image filled with software.

**Comment by dennisameling** [comment]
> the x64 version of GfW should be fine for now as Windows can emulate it.

Just FYI, Git for Windows is now available as a native arm64 version as well: https://github.com/git-for-windows/git/issues/3107#issuecomment-2498275856 🎉

**Comment by lilith** [comment]
Is the emulated git just not in path? Pwsh, bash, vs, msvc, Rust, etc seem to be missing.

**Comment by jasonrandrews** [comment]
Sorry for the delays, every single step of this project has hit unexpected issues. 
The initial testing uncovered new issues, and we are working with the Azure support team to sort it out.

**Comment by lemonmojo** [comment]
@jasonrandrews What's the current status?

**Comment by jasonrandrews** [comment]
No change, still highest priority and working with the Azure support team.

**Comment by oberrich** [comment]
After two days of trial and error and a big fat bill from Bill, I've finally managed to use Rust and `bindgen` on the `Windows ARM64` runner.

```yml
name: "cargo"
on:
  workflow_dispatch: 
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
env:
  CARGO_TERM_COLOR: always
jobs:
  bindgen:
    strategy:
      matrix:
        os: [windows-11-preview_aarch64, windows-2025]
        target: [aarch64-pc-windows-msvc, x86_64-pc-windows-msvc, i686-pc-windows-msvc]
        exclude:
          - os: windows-11-preview_aarch64
            target: x86_64-pc-windows-msvc
          - os: windows-11-preview_aarch64
            target: i686-pc-windows-msvc
          - os: windows-2025
            target: aarch64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
    - name: Download LLVM (aarch64)
      if: matrix.os == 'windows-11-preview_aarch64'
      uses: robinraju/release-downloader@v1
      with:
        repository: 'llvm/llvm-project'
        tag: 'llvmorg-19.1.5'
        filename: 'LLVM-19.1.5-woa64.exe'
        
    - name: Install LLVM (aarch64)
      if: matrix.os == 'windows-11-preview_aarch64'
      run: |
        Start-Process -FilePath "LLVM-19.1.5-woa64.exe" -ArgumentList '/S' -NoNewWindow -Wait
        
    - name: Install Build Tools (aarch64)
      if: matrix.os == 'windows-11-preview_aarch64'
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')) 
        Add-Content -Path $env:GITHUB_PATH -Value "C:\ProgramData\chocolatey\bin" -Encoding utf8
        choco install visualstudio2022buildtools -y --no-progress --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.ARM64 --add Microsoft.VisualStudio.Component.Windows11SDK.22621"

    - name: Install Nightly Rust (aarch64)
      if: matrix.os == 'windows-11-preview_aarch64'
      run: |
        Add-Content -Path $env:GITHUB_PATH -Value "$env:USERPROFILE\.cargo\bin" -Encoding utf8
        Invoke-WebRequest -Uri "https://win.rustup.rs/aarch64" -OutFile "$env:RUNNER_TEMP\rustup-init.exe"
        & "$env:RUNNER_TEMP\rustup-init.exe" --default-host aarch64-pc-windows-msvc --default-toolchain nightly -y

    - name: Download Git for Windows (aarch64)
      if: matrix.os == 'windows-11-preview_aarch64'
      uses: robinraju/release-downloader@v1
      with:
        repository: 'git-for-windows/git'
        tag: 'v2.48.0-rc1.windows.1'
        filename: 'Git-2.48.0-rc1-arm64.exe'
        
    - name: Install Git for Windows (aarch64)
      if: matrix.os == 'windows-11-preview_aarch64'
      run: |
        Start-Process -FilePath "Git-2.48.0-rc1-arm64.exe" -ArgumentList "/VERYSILENT" -NoNewWindow -Wait
        Add-Content -Path $env:GITHUB_PATH -Value "C:\Program Files\Git\cmd" -Encoding utf8
        Add-Content -Path $env:GITHUB_PATH -Value "C:\Program Files\Git\bin" -Encoding utf8
        
    - name: Install Rust
      if: matrix.os != 'windows-11-preview_aarch64'
      uses: dtolnay/rust-toolchain@nightly
      with:
        targets: ${{ matrix.target }}
        components: rustfmt
        
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Build
      run: |
        cargo build -vv -F regenerate --target ${{ matrix.target }}
```

This downloads and installs
- Git for Windows (Bash)
- LLVM (Clang, required for `bindgen`)
- Visual Studio 2022 Build Tools 
- Rust (nightly)

This assumes your ARM64 runner's name is `windows-11-preview_aarch64` and takes around 10 minutes to complete on the 16-core machine.
