### ISSUE TITLE
actions/setup-python@v5 failing on ARM64 Runners

### ISSUE THREAD

**Issue by ukumar-dev** [actions/partner-runner-images#4]
Below mentioned PR is critical for smooth migration to Arm64 runners.

This code fails on Arm64 runners:
```
     - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
```
https://github.com/actions/python-versions/pull/274
