### ISSUE TITLE
actions/checkout@v4 SIGSEGV (exit code 139) in ubuntu-24.04-arm

### ISSUE THREAD

**Issue by MikeMcC399** [actions/partner-runner-images#47]
## Issue

The step

```yaml
- uses: actions/checkout@v4
```

sporadically fails in `ubuntu-24.04-arm`.

> ##[debug]Node Action run completed with exit code 139

This indicates `SIGSEGV`.

If the job is re-run, the step is often successful.

This is in a workflow with parallel runs with the `matrix:` construct. If I strip out the workflow to only include the checkout step and then run it, I got no failure in five attempts.

I have also observed it using `matrix:` with only one combination:

```yaml
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
```

## Logs

See for example https://github.com/cypress-io/cypress-docker-images/actions/runs/13159700085/job/36725026693

![Image](https://github.com/user-attachments/assets/923f29be-f781-4dbb-90a3-1104f0cee5ef)

## Related

- Also mentioned in https://github.com/actions/partner-runner-images/issues/37
