### ISSUE TITLE
DBUS_SESSION_BUS_ADDRESS error on Linux arm64 22.04 larger runner

### ISSUE THREAD

**Issue by dennisameling** [actions/partner-runner-images#53]
We're working on https://github.com/signalapp/ringrtc/pull/61 to build Signal's RingRTC on native Linux arm64 runners.

However, we're observing a weird difference between the new `ubuntu-22.04-arm` runner [that's now in Public Preview](https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/) and larger (org-level) Ubuntu 22.04 runners. According to the GitHub documentation, they should be using the exact same [Ubuntu 22.04 Partner Images](https://github.com/actions/partner-runner-images/blob/main/images/arm-ubuntu-22-image.md) and therefore should behave consistently. That doesn't seem to be the case.

Confirming that my org-level `ubuntu-22.04-arm-dennis` is using the `Ubuntu 22.04 by Arm Limited image` and not a custom one:

![Image](https://github.com/user-attachments/assets/3c8da15d-a11f-45fa-a6a6-845e0c012fd5)

Here you can see the difference for the exact same pipeline:

- Using the `ubuntu-22.04-arm` Public Preview runner, the "Install dependencies" step [works without problems](https://github.com/dennisameling/ringrtc/actions/runs/13266644700/job/37035642314?pr=4#step:2:367).
- Using the `ubuntu-22.04-arm-dennis` (org-level) runner, the "Install dependencies" [fails with](https://github.com/dennisameling-org/ringrtc/actions/runs/13302527820/job/37146416395#step:2:367):

```
Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)
Error: Process completed with exit code 1.
```

Could it be that there's a difference between the machines or images that run on the new Public Preview runners vs. the larger org-level ones? Thanks!

## Reproduction steps

Pipeline using the public ubuntu-22.04-arm runner: https://github.com/dennisameling/ringrtc/blob/refs/heads/arm64-native-tmp/.github/workflows/ringrtc.yml#L113

Pipeline using org-level larger ubuntu-22.04-arm-dennis runner: https://github.com/dennisameling-org/ringrtc/blob/arm64-native-tmp/.github/workflows/ringrtc.yml#L114

**Comment by dennisameling** [comment]
Was just comparing the output of `env` on the `ubuntu-22.04-arm` vs. the `ubuntu-22.04-arm-dennis` runner and noticed that `XDG_RUNTIME_DIR` is indeed missing on the larger runner:

<img width="1197" alt="Image" src="https://github.com/user-attachments/assets/d166e3b5-15e7-4c4b-891b-0e7704af423f" />

There seems to be a slight config change on the `ubuntu-22.04-arm` runner vs the larger runners.

I was able to [fix my pipeline](https://github.com/dennisameling-org/ringrtc/actions/runs/13486179584/job/37677593169) by adding this step:

```yaml
    steps:
    # https://github.com/actions/partner-runner-images/issues/53
    - name: Work around XDG_RUNTIME_DIR error on Linux arm64
      if: startsWith(matrix.os, 'ubuntu-22.04-arm')
      run: |
        echo "UID is $UID. Setting XDG_RUNTIME_DIR to /run/user/$UID"
        sudo systemctl start user@$UID.service
        echo "XDG_RUNTIME_DIR=/run/user/$UID" >> $GITHUB_ENV
```

@maxim-lobanov given that you or your team fixed the issue with `XDG_CONFIG_HOME` in a [probably slightly related issue](https://github.com/actions/partner-runner-images/issues/27), I'm tagging you here if that's OK. Do you have any thoughts on this?
