### ISSUE TITLE
windows-arm-latest-large: bash: command not found

### ISSUE THREAD

**Issue by nichoj10** [actions/partner-runner-images#55]
### Description

We have a step in our build pipeline that invokes bash to execute a git command. Running this step on the `windows-arm-latest-large` image returns an error with:
```
bash: command not found
```
This documentation suggests to me that bash should be available on the windows arm images: https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md. We've found the command runs fine on the windows-latest-large image.

Step:
```
steps:
  - name: Set up git for Windows
    if: ${{ inputs.target_os == 'windows' }}
    shell: bash
    run: git config --system core.longpaths true
```
