### ISSUE TITLE
Feat: Add Rust toolchain to windows-11-arm

### ISSUE THREAD

**Issue by yorickdowne** [actions/partner-runner-images#77]
**Type of issue**
- [x] Request for additional tools or software for an existing image.

**Describe the issue**

`windows-11-arm` runner currently does not come with the Rust toolchain pre-installed

In testing, that environment is supported and something like this can add Rust:

```
      - name: Install rustup (Windows 11 ARM64)
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://static.rust-lang.org/rustup/dist/aarch64-pc-windows-msvc/rustup-init.exe" -OutFile rustup-init.exe
          .\rustup-init.exe --default-toolchain none -y
          "$env:USERPROFILE\.cargo\bin" | Out-File -Append -Encoding ascii $env:GITHUB_PATH
          "CARGO_HOME=$env:USERPROFILE\.cargo" | Out-File -Append -Encoding ascii $env:GITHUB_ENV
      - name: Install Rust (Windows 11 ARM64)
        shell: pwsh
        run: |
          rustup install stable
          rustup target add aarch64-pc-windows-msvc

```

**Desired functionality**

Have a Rust toolchain preinstalled in the `windows-11-arm` image

**Comment by alex** [comment]
FYI, this also isn't listed in the "Omitted Software" part of the docs: https://github.com/actions/partner-runner-images/blob/main/images/arm-windows-11-image.md#omitted-software

Much better to simply add it though :-)

**Comment by riverar** [comment]
+1 Hit this while testing Arm runners in the Rust for Windows repository.

**Comment by AsherJingkongChen** [comment]
For anyone who wants to install `rustup` in **bash** before `actions-rust-lang/setup-rust-toolchain`, so there will be no more error `rustup: command not found` occurs in your GitHub Action experimental ARM64 runner. You can skip the step after the issue closed.

```yml
            - if: matrix.os == 'windows-11-arm'
              name: Install rustup on Windows ARM
              run: |
                  curl -LOs https://static.rust-lang.org/rustup/dist/aarch64-pc-windows-msvc/rustup-init.exe
                  ./rustup-init.exe -y --default-toolchain none --no-modify-path
                  echo "$USERPROFILE/.cargo/bin" >> "$GITHUB_PATH"
            - uses: actions-rust-lang/setup-rust-toolchain@v1
```
