### ISSUE TITLE
windows-11-arm defaults to End-of-Life Node.js v19.9.0

### ISSUE THREAD

**Issue by MikeMcC399** [actions/partner-runner-images#78]
**Type of issue**
- [ ] Error when running a workflow.
- [ ] Request for additional tools or software for an existing image.
- [ ] Request for a new image, Linux or Windows.
- [x] Other

**Describe the issue**

The `windows-11-arm` image defaults to using [Node.js v19.9.0](https://nodejs.org/en/blog/release/v19.9.0), released on April 12, 2023 and which entered [End-of-Life status](https://github.com/nodejs/release#release-schedule) on June 1, 2023.

**To Reproduce**

Run the following workflow

```yaml
name: show-node-version
on:
  workflow_dispatch:

jobs:
  show-default-node:
    runs-on: windows-11-arm
    steps:
      - run: node -v
```

**Expected behavior**

The default Node.js version should be a supported [Node.js LTS](https://github.com/nodejs/release#release-schedule) version such as [Node.js v22.14.0](https://nodejs.org/en/blog/release/v22.14.0) or above.

It should **not** be an unsupported version of Node.js.

Unsupported versions of Node.js should not be cached in the image.

**Screenshots**

![Image](https://github.com/user-attachments/assets/671b1fe5-952d-4b5b-b07f-18bfbf1b6ce1)

**Desktop (please complete the following information):**
 - OS: windows-11-arm
