### ISSUE TITLE
[windows-11-arm] Install native arm64 Ninja

### ISSUE THREAD

**Issue by Wunkolo** [actions/partner-runner-images#96]
**Type of issue**
- [ ] Error when running a workflow.
- [x] Request for additional tools or software for an existing image.
- [ ] Request for a new image, Linux or Windows.
- [ ] Other

**Describe the issue**
Currently the `windows-11-arm` runner does not support [Ninja](https://github.com/ninja-build/ninja) while the [x64 windows runners do](https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md#tools).

```
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
```

Ninja has supported native Windows-Arm builds for about a year now:
https://github.com/ninja-build/ninja/releases

**Desktop (please complete the following information):**
 - OS: `windows-11-arm`

**Comment by mstorsjo** [comment]
+1, https://github.com/actions/runner-images/issues/11391 concluded that ninja now is preinstalled in all macos, windows and ubuntu images - however it is still missing in the windows-11-arm images.

**Comment by crudelios** [comment]
+1, please add this, it's a widely used build tool.

**Comment by jeremyd2019** [comment]
Looks like it's there now
```
# which ninja
/c/Tools/Ninja/ninja

# file /c/Tools/Ninja/ninja.exe
/c/Tools/Ninja/ninja.exe: PE32+ executable for MS Windows 6.02 (console), ARM64, 6 sections
```

**Comment by mstorsjo** [comment]
> Looks like it's there now
> 
> ```
> # which ninja
> /c/Tools/Ninja/ninja
> 
> # file /c/Tools/Ninja/ninja.exe
> /c/Tools/Ninja/ninja.exe: PE32+ executable for MS Windows 6.02 (console), ARM64, 6 sections
> ```

That's odd - I tried running a test action like this:
```
  inspect-windows:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - windows-2022
          - windows-2025
          - windows-11-arm
    runs-on: ${{matrix.runner}}
    steps:
      - name: Inspect ninja
        shell: cmd
        run: |
          ninja --version
          where ninja
```

And on `windows-11-arm`, this ends up with:
```
'ninja' is not recognized as an internal or external command,
operable program or batch file.
INFO: Could not find files for the given pattern(s).
```

So this directory doesn't seem to be in PATH by default in cmd (and presumably powershell) - I presume you tested with msys2?
